### ISSUE TITLE
Definir padrões para criação de novas issues

### ISSUE THREAD

**Issue by mateusrovedaa** [aztecweb/lista-de-compras#2]
## Descrição
Manter padrões em um projeto é extremamente importante para mantermos as coisas organizadas e de fácil entendimento. Acredito que uma discussão válida para fazermos no início do projeto é sobre criarmos padrões para a criação de novas issues aqui no repositório do projeto, facilitando o entendimento por parte da comunidade e concentrando as informações necessárias para um bom andar das tarefas.

## Objetivo
Discutir e definir um padrão para ser utilizado na criação de novas issues.

**Comment by marcosvile** [comment]
Recomendação de leitrura: 


https://medium.com/trainingcenter/melhorando-issues-para-ficarem-mais-amig%C3%A1veis-para-iniciantes-890b0bad4b9

**Comment by aldair-meneses** [comment]
> Recomendação de leitura:
> 
> https://medium.com/trainingcenter/melhorando-issues-para-ficarem-mais-amig%C3%A1veis-para-iniciantes-890b0bad4b9

Achei uma ótima indicação de leitura.
Alguns pontos que achei essencial retirados apartir da leitura:

* As issues devem ser de fácil entendimento para pessoas de qualquer nível e mesmo para aquelas não estão envolvidas no projeto.
* O titulo da issue como uma pre-descrição do problema. Exemplo: Adicionar função de limpar a lista de compras.
* Qual o motivo da issue existir e possíveis soluções já tentadas.
* O que a issue soluciona quando concluída.
* Como solucionar a Issue.

Acho interessante adicionar.
* Issues por tipos. Exemplo: bugs, tarefas.
* Issues por hierarquia, ou seja, issues que são mais importantes que outras e devem ser prioridades em relação a outra.

**Comment by marcosvile** [comment]
### Padronizar a descrição das issues e utilizar as labels para melhor classificação.


#### Exemplos:

[Sugestão][Padronizar a descrição das issues]

Padronizar a descrição das issues com base em um template, para melhorar o custume de criar uma issue bem elaborada e objetiva para o melhor entendimento da equipe.


## TEMPLATES
========================================================

[Documentação][Título]

{
texto
}

| codigo
| codigo
| codigo  (se necessário)

{
texto
}

========================================================


[Dúvidas][Título]

{
texto
}

| codigo
| codigo
| codigo  (se necessário)

{
texto
}

========================================================

[Sugestões][Título]

{
texto
}

| codigo
| codigo
| codigo  (se necessário)

{
texto
}

========================================================

[BUG][Título]

{
texto
}

| codigo
| codigo
| codigo  (se necessário)

{
texto
}

========================================================


### utilização das labels para melhor classificação das issues.

**Comment by mateusrovedaa** [comment]
Concordo que labels vão ajudar, principalmente com um quadro Kanban.

Quanto a forma de escrita, podemos criar um modelo em Markdown que pode ser copiado para cada nova issue, então alteramos tudo o que precisamos e criamos a nova issue.

**Comment by RaisaSampaio** [comment]
Vou deixar aqui o link que achei de como criar um modelo/template aqui no GitHub.
https://docs.github.com/pt/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by mblithium** [comment]
O formato "[tipo]: Descrição" pode ser uma boa ideia para manter mais organizado, juntamente com o sistema de labels do próprio Github. 

**Exemplos:**
[BUG]: O botão de adicionar novos itens não está funcionando.
[Sugestão]: Adicionar opção de tema escuro na aplicação.
[Feedback]: O menu principal poderia estar no canto superior direito, como era antes.
[TO-DO]: Adicionar os ícones dos tipos de produtos. (só uma sugestão opcional, para devs se comunicarem sobre um recurso que já está certo que será feito ou precisa fazer)

**E para criar um padrão, utilizar templates para a pessoa preencher dependendo do tipo de issue, como o exemplo a seguir:**

**[BUG]: O botão de adicionar novos itens não está funcionando.**
**Descrição:** Ao clicar no botão para adicionar novos itens na lista, nada acontece.
**Onde ocorre:** na página principal, embaixo da lista de compras no canto inferior direito.
**Passos para reproduzir o problema:** Na página inicial, escreva algo na caixa e clique no botão de adicionar novos itens na lista.
**Ambiente e informações adicionais:** testado no Firefox/100.2.0 e Chrome/43.0.2357.65.

**[Sugestão]: Adicionar opção de tema escuro na aplicação.**
**Descrição:**  Uma opção nas configurações para o usuário escolher um tema escuro da interface.
**Onde:** Em toda a interface. (se fosse específico, diria que está na caixa X da página Y)
**Motivo:** Acredito que seja interessante ter essa opção, para quem estiver a ver de noite e evitar de queimar os olhos.

**[Feedback]: O menu principal poderia estar no canto superior direito, como era antes.**
**Descrição:**  Achei difícil e meio esquisito ter que ir ao canto superior esquerdo para abrir um menu, poderia estar no canto superior direito no header.
**Recurso:** menu "hambúrguer" do header.

**[TO-DO]: Adicionar os ícones dos tipos de produtos.**
**Descrição:** Adicionar os ícones dos tipos de produtos ao projeto.
**Passos:** 

- [x] - procurar ícones dos produtos coerentes que hamonizem com a interface, tomando cuidado com as licenças;
- [ ] - ajustar os tamanhos e otimizar para web;  
- [ ] - adicionar ao projeto e testar;
- [ ] - fazer um pull request com as alterações.

**Colaboradores:** @ dev1 @ dev2 @ dev5 (quem está trabalhando nisso)

Acredito que isso será melhorado no futuro, pois com o tempo veremos as necessidades e algum padrão nos tipos de issues, isso seria só uma sugestão para os templates iniciais.

**Comment by mblithium** [comment]
Talvez esse artigo seja útil, sobre os templates de Issues e PRs: https://docs.github.com/pt/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by marcosvile** [comment]
Sugiro seguirmos inicialmente com a sugestão de @mblithium com a configuração de [modelos](https://docs.github.com/pt/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) forncedidos pelo github.

**Comment by mateusrovedaa** [comment]
@mblithium revisar e sugerir um padrão.
